apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payment
commonLabels:
  app: dashboard-service
resources:
  - deployment.yml
  - service.yml
  - config/autoscaling.yml
  - config/configmap.yml
  - config/namespace.yml
