apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app: dashboard-service
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
